In [ ]:
# np.sort - Sort an array along a specified axis.
# resources link: https://numpy.org/doc/stable/reference/generated/numpy.sort.html
import numpy as np
a = np.random.randint(1,100,15)
a

array([30, 89, 70,  4, 52, 24, 93, 89, 59, 43, 99, 56, 83,  3, 60],
      dtype=int32)

In [8]:
np.sort(a)[::-1] # sort in descending order

array([99, 93, 89, 89, 83, 70, 60, 59, 56, 52, 43, 30, 24,  4,  3],
      dtype=int32)

In [4]:
b= np.random.randint(1, 100, 24).reshape(6,4)
b

array([[ 5, 25, 21,  4],
       [99, 95, 35, 36],
       [32, 93, 45, 46],
       [59, 36, 90, 44],
       [28, 15, 55, 80],
       [79, 95, 74,  5]], dtype=int32)

In [ ]:
np.sort(b)
# row wise sorting

array([[ 4,  5, 21, 25],
       [35, 36, 95, 99],
       [32, 45, 46, 93],
       [36, 44, 59, 90],
       [15, 28, 55, 80],
       [ 5, 74, 79, 95]], dtype=int32)

In [7]:
np.sort(b, axis=0) # sort each column

array([[ 5, 15, 21,  4],
       [28, 25, 35,  5],
       [32, 36, 45, 36],
       [59, 93, 55, 44],
       [79, 95, 74, 46],
       [99, 95, 90, 80]], dtype=int32)

In [9]:
# np.append - Append values to the end of an array.
# resources link: https://numpy.org/doc/stable/reference/generated/numpy.append.html

a 

array([30, 89, 70,  4, 52, 24, 93, 89, 59, 43, 99, 56, 83,  3, 60],
      dtype=int32)

In [10]:
np.append(a, 2000) # append a single value

array([  30,   89,   70,    4,   52,   24,   93,   89,   59,   43,   99,
         56,   83,    3,   60, 2000])

In [11]:
b

array([[ 5, 25, 21,  4],
       [99, 95, 35, 36],
       [32, 93, 45, 46],
       [59, 36, 90, 44],
       [28, 15, 55, 80],
       [79, 95, 74,  5]], dtype=int32)

In [14]:
np.append(b, np.ones((b.shape[0],1)),axis=1) # append a column of ones to the end of the array

array([[ 5., 25., 21.,  4.,  1.],
       [99., 95., 35., 36.,  1.],
       [32., 93., 45., 46.,  1.],
       [59., 36., 90., 44.,  1.],
       [28., 15., 55., 80.,  1.],
       [79., 95., 74.,  5.,  1.]])

In [15]:
# np.concatenate - Join a sequence of arrays along an existing axis.
# resources link: https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [16]:
np.concatenate((c,d), axis=0) # concatenate along rows (vertical stacking) 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [17]:
np.concatenate((c,d), axis=1) # concatenate along columns (horizontal stacking)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [18]:
# np.unique - Find the unique elements of an array.
# resources link: https://numpy.org/doc/stable/reference/generated/numpy.unique.html

e = np.array([1,2,3,4,5,5,6,7,8,8,9])
e

array([1, 2, 3, 4, 5, 5, 6, 7, 8, 8, 9])

In [19]:
np.unique(e)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
# np.expand_dims - Expand the shape of an array.   
# resources link: https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [ ]:
np.expand_dims(a, axis=1) 
# adds a new axis at position 1, transforming the shape from (5,) to (5, 1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
np.expand_dims(a, axis=0) # add a new axis at the beginning (row vector)
# transforms the shape from (5,) to (1, 5)

array([[1, 2, 3, 4, 5]])

In [25]:
# np.where - Return elements chosen from x or y depending on condition.
# resources link: https://numpy.org/doc/stable/reference/generated/numpy.where.html
a = np.array([11,34,22,56,66,77,86,90,100])
a

array([ 11,  34,  22,  56,  66,  77,  86,  90, 100])

In [26]:
np.where(a > 50) # returns the indices of elements greater than 50

(array([3, 4, 5, 6, 7, 8]),)

In [27]:
np.where(a<50) # returns the indices of elements less than 50

(array([0, 1, 2]),)

In [ ]:
np.where(a>50, 0, a) # replace elements greater than 50 with 0, keep others unchanged
# np.where(condition, true_value, false_value) 

array([11, 34, 22,  0,  0,  0,  0,  0,  0])

In [ ]:
np.where(a%2==0, 0, a) 
# replace even numbers with 0, keep odd numbers unchanged

array([11,  0,  0,  0,  0, 77,  0,  0,  0])

In [30]:
# np.argmax - Returns the indices of the maximum values along an axis.
# resources link: https://numpy.org/doc/stable/reference/generated/numpy.argmax.html
a

array([ 11,  34,  22,  56,  66,  77,  86,  90, 100])

In [31]:
np.argmax(a) # returns the index of the maximum value in the array

np.int64(8)

In [32]:
b

array([[ 5, 25, 21,  4],
       [99, 95, 35, 36],
       [32, 93, 45, 46],
       [59, 36, 90, 44],
       [28, 15, 55, 80],
       [79, 95, 74,  5]], dtype=int32)

In [33]:
np.argmax(b, axis=0) # returns the indices of the maximum values along each column

array([1, 1, 3, 4])

In [34]:
np.argmax(b, axis=1) # returns the indices of the maximum values along each row

array([1, 0, 1, 2, 3, 1])

In [35]:
# np.argmin - Returns the indices of the minimum values along an axis.
# resources link: https://numpy.org/doc/stable/reference/generated/numpy.argmin.html

a

array([ 11,  34,  22,  56,  66,  77,  86,  90, 100])

In [36]:
np.argmin(a) # returns the index of the minimum value in the array

np.int64(0)

In [37]:
b

array([[ 5, 25, 21,  4],
       [99, 95, 35, 36],
       [32, 93, 45, 46],
       [59, 36, 90, 44],
       [28, 15, 55, 80],
       [79, 95, 74,  5]], dtype=int32)

In [38]:
np.argmin(b, axis=0) # returns the indices of the minimum values along each column

array([0, 4, 0, 0])

In [39]:
# np.cumsum - Return the cumulative sum of the elements along a given axis.
# resources link: https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

a

array([ 11,  34,  22,  56,  66,  77,  86,  90, 100])

In [41]:
np.cumsum(a) # returns the cumulative sum of the elements in the array

array([ 11,  45,  67, 123, 189, 266, 352, 442, 542])

In [42]:
b

array([[ 5, 25, 21,  4],
       [99, 95, 35, 36],
       [32, 93, 45, 46],
       [59, 36, 90, 44],
       [28, 15, 55, 80],
       [79, 95, 74,  5]], dtype=int32)

In [43]:
np.cumsum(b, axis=0) # returns the cumulative sum along each column

array([[  5,  25,  21,   4],
       [104, 120,  56,  40],
       [136, 213, 101,  86],
       [195, 249, 191, 130],
       [223, 264, 246, 210],
       [302, 359, 320, 215]])