## **What is numpy?**

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

## **Numpy Arrays Vs Python Sequences**

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### **Creating Numpy Arrays**

In [3]:
pip install numpy

   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   -----------------


[notice] A new release of pip is available: 25.2 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

In [5]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [ ]:
# 1D array or vector
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# 2D arrays or matrix
b= np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [15]:
# 3D arrays or tensor
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [19]:
# dtype
np.array([1,2,3], dtype = float)

array([1., 2., 3.])

In [20]:
np.array([0,1,2], dtype = bool)

array([False,  True,  True])

In [21]:
# np range

np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [25]:
# with reshape
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
np.arange(1,13).reshape(3,4) # 3 row 4 col

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
np.arange(16).reshape(2,2,4) # 2 blocks, 2 rows, 4 col

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [ ]:
# np.ones and np.zeros 
# Used for initialization of arrays

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [34]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [41]:
# np.random - used to create random numbers of arrays

np.random.random((1,2))

array([[0.37725879, 0.72025804]])

In [ ]:
# np.linspace-return evenly spaced numbers over a specified interval
np.linspace(-10,10,5) # start, stop, number of elements

array([-10.,  -5.,   0.,   5.,  10.])

In [46]:
np.linspace(-10,10,5,dtype=int) 

array([-10,  -5,   0,   5,  10])

In [45]:
# np.identity - returns identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### **Array Attributes**

In [50]:
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [51]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [53]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [60]:
# ndim - number of dimensions
print(a1.ndim,'D array')
print(a2.ndim,'D array')
print(a3.ndim,'D array')

1 D array
2 D array
3 D array


In [ ]:
# shape - number of elements in each dimension
print(a1.shape)
print(a2.shape)
print(a3.shape) # (2,2,2) - 2 blocks, 2 rows, 2 col

(10,)
(3, 4)
(2, 2, 2)


In [63]:
# size - number of elements in the array
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [ ]:
# itemsize - size in bytes of each element in the array
# int32 = 4 bytes, int64 = 8 bytes, float32 = 4 bytes, float64 = 8 bytes
print(a1.itemsize,'bytes')
print(a2.itemsize,'bytes')
print(a3.itemsize,'bytes')

8 bytes
8 bytes
8 bytes


In [66]:
# dtype - data type of the elements in the array
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64
