## **What is numpy?**

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

## **Numpy Arrays Vs Python Sequences**

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### **Creating Numpy Arrays**

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.2 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

In [4]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [5]:
# 1D array or vector
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
# 2D arrays or matrix
b= np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
# 3D arrays or tensor
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [8]:
# dtype
np.array([1,2,3], dtype = float)

array([1., 2., 3.])

In [9]:
np.array([0,1,2], dtype = bool)

array([False,  True,  True])

In [10]:
# np range

np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [12]:
# with reshape
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [14]:
np.arange(1,13).reshape(3,4) # 3 row 4 col

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [15]:
np.arange(16).reshape(2,2,4) # 2 blocks, 2 rows, 4 col

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [16]:
# np.ones and np.zeros 
# Used for initialization of arrays

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
# np.random - used to create random numbers of arrays

np.random.random((1,2))

array([[0.07087677, 0.12994706]])

In [19]:
# np.linspace-return evenly spaced numbers over a specified interval
np.linspace(-10,10,5) # start, stop, number of elements

array([-10.,  -5.,   0.,   5.,  10.])

In [20]:
np.linspace(-10,10,5,dtype=int) 

array([-10,  -5,   0,   5,  10])

In [21]:
# np.identity - returns identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### **Array Attributes**

In [22]:
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [23]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [25]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [26]:
# ndim - number of dimensions
print(a1.ndim,'D array')
print(a2.ndim,'D array')
print(a3.ndim,'D array')

1 D array
2 D array
3 D array


In [27]:
# shape - number of elements in each dimension
print(a1.shape)
print(a2.shape)
print(a3.shape) # (2,2,2) - 2 blocks, 2 rows, 2 col

(10,)
(3, 4)
(2, 2, 2)


In [28]:
# size - number of elements in the array
print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [29]:
# itemsize - size in bytes of each element in the array
# int32 = 4 bytes, int64 = 8 bytes, float32 = 4 bytes, float64 = 8 bytes
print(a1.itemsize,'bytes')
print(a2.itemsize,'bytes')
print(a3.itemsize,'bytes')

8 bytes
8 bytes
8 bytes


In [30]:
# dtype - data type of the elements in the array
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


#### Changing datatype

In [32]:
# astype - to change the data type of the array
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [34]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [35]:
# Scalar operations 
# arithmetic operations that can be performed on arrays
# a1 + 10
# a1 - 10
# a1 * 10
# a1 / 10
# a1 ** 2

a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [36]:
# relational operations
a1 > 5

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [39]:
# vector operations
# arithmetic operations that can be performed on arrays of the same shape
print(a1)
print('\n')
print(a2)
print('\n')
print(a1 + a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]


###  **Array Functions**

### Max/Min/Sum/Prod

In [40]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[63., 76., 75.],
       [60., 96., 90.],
       [57., 29.,  2.]])

In [41]:
np.min(a1)

np.float64(2.0)

In [43]:
np.max(a1)

np.float64(96.0)

In [44]:
np.sum(a1)

np.float64(548.0)

In [45]:
np.prod(a1)

np.float64(615436496640000.0)

In [47]:
# axis - 0 for columns, 1 for rows
print(np.max(a1, axis=0)) # max of each column
print(np.max(a1, axis=1)) # max of each row

[63. 96. 90.]
[76. 96. 57.]


In [49]:
print(np.sum(a1, axis = 0)) # sum of each column
print(np.sum(a1, axis = 1)) # sum of each row

[180. 201. 167.]
[214. 246.  88.]


### Mean, Median, Standard Deviation, Variance, Trigo 

In [50]:
np.mean(a1)

np.float64(60.888888888888886)

In [51]:
np.median(a1)

np.float64(63.0)

In [52]:
np.std(a1)

np.float64(27.91433102446143)

In [53]:
np.var(a1)

np.float64(779.2098765432098)

In [54]:
np.sin(a1)

array([[ 0.1673557 ,  0.56610764, -0.38778164],
       [-0.30481062,  0.98358775,  0.89399666],
       [ 0.43616476, -0.66363388,  0.90929743]])

### Arrays Dot Product

In [58]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3) 
print(a2)
print('\n')
print(a3)
# (12, 24) = 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23
print('\n')
print(np.dot(a2,a3))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


[[114 120 126]
 [378 400 422]
 [642 680 718]]


### Log and Exp function

In [59]:
np.log(a1)

array([[4.14313473, 4.33073334, 4.31748811],
       [4.09434456, 4.56434819, 4.49980967],
       [4.04305127, 3.36729583, 0.69314718]])

In [60]:
np.exp(a1)

array([[2.29378316e+27, 1.01480039e+33, 3.73324200e+32],
       [1.14200739e+26, 4.92345829e+41, 1.22040329e+39],
       [5.68572000e+24, 3.93133430e+12, 7.38905610e+00]])

### Round, Floor, Ceil

In [61]:
np.random.random((2,3))

array([[0.10770338, 0.32742906, 0.82656219],
       [0.57209427, 0.36104973, 0.5893668 ]])

In [62]:
np.random.random((2,3))*100

array([[12.73783299, 72.0731762 , 23.26483766],
       [25.13328245, 56.63575573, 38.5829432 ]])

In [ ]:
np.round(np.random.random((2,3))*100) # round to nearest integer

array([[52., 43., 32.],
       [ 4., 15.,  4.]])

In [ ]:
np.ceil(np.random.random((2,3))*100) # round up to nearest integer

array([[26.,  3.,  7.],
       [ 7., 89., 71.]])

In [ ]:
np.floor(np.random.random((2,3))*100) # round down to nearest integer

array([[98.,  4., 79.],
       [89., 33., 78.]])

### Indexing & Slicing

In [ ]:
# indexing - accessing individual elements in the array 

a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [68]:
print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [69]:
a1[0] # first element

np.int64(0)

In [70]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [72]:
a2[1,2] # element in 2nd row, 3rd column

np.int64(6)

In [73]:
a2[1,0]

np.int64(4)

In [74]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[1,0,1] # element in 2nd block, 1st row, 2nd column

np.int64(5)

In [76]:
a3[0,1,0] # element in 1st block, 2nd row, 1st column

np.int64(2)

In [77]:
# Slicing - extracting a portion of the array

a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
a1[2:5] # elements from index 2 to 4

array([2, 3, 4])

In [83]:
a1[2:8:1] # elements from index 2 to 7 with step of 1

array([2, 3, 4, 5, 6, 7])

In [84]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[0,:] # all elements in the first row
# here a2[0,:] means we want all columns in the first row (index 0) of a2

array([0, 1, 2, 3])

In [ ]:
a2[:,2] # all elements in the third column
# here a2[:,2] means we want all rows in the third column (index 2) of a2

array([ 2,  6, 10])

In [ ]:
a2[1:,1:3]
# here a2[1:,1:3] means we want all rows from index 1 to the end and columns from index 1 to 2 (3 is exclusive) of a2

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a2[:] # all elements in a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [103]:
a2[::] # all elements in a2 (same as a2[:])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[::2]
#  here a2[::2] means all rows and columns with a step of 2, so we get every 2nd row and every 2nd column of a2

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [101]:
a2[::3]
# here a2[::3] means we want every 3rd row and every 3rd column of a2

array([[0, 1, 2, 3]])

In [104]:
a2[::-3]

array([[ 8,  9, 10, 11]])

In [105]:
a2[:,::3]

array([[ 0,  3],
       [ 4,  7],
       [ 8, 11]])

In [ ]:
a2[::2,::3]
# here a2[::2,::3] means we want every 2nd row and every 3rd column of a2

array([[ 0,  3],
       [ 8, 11]])

In [ ]:
a2[::2, 1::2]
# here a2[::2, 1::2] means we want every 2nd row and every 2nd column starting from index 1 of a2

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a2[1::2, ::3]
# here a2[1::2, ::3] means we want every 2nd row starting from index 1 and every 3rd column of a2

array([[4, 7]])

In [ ]:
a2[0:2,1:] 
# here a2[0:2,1:] means we want rows from index 0 to 1 (2 is exclusive) and all columns from index 1 to the end of a2

array([[1, 2, 3],
       [5, 6, 7]])

In [138]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [139]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [150]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[0, 1, :]
# here a3[0, 1:2] means we want the first block (index 0) and rows from index 1 to 1 (2 is exclusive) of a3

array([3, 4, 5])

In [ ]:
a3[1,2,1:2]
# here a3[1,2,1:2] means we want the second block (index 1) and the third row (index 2) and columns from index 1 to 1 (2 is exclusive) of a3

array([16])

In [191]:
a3[2, 1:, 1:]
# here a3[2, 1::, 1:] means we want the third block (index 2) and all rows from index 1 to the end and all columns from index 1 to the end of a3

array([[22, 23],
       [25, 26]])

In [206]:
a3[::2, 0, ::2]
# here a3[0::2, 0::3, ::2] means we want every 2nd block starting from index 0, every 3rd row starting from index 0 and every 2nd column of a3

array([[ 0,  2],
       [18, 20]])

### Iteration on NumPy Array

### Reshaping - Transpose, Ravel

###  Stacking - vstack, hstack

### Splitting - hsplit, vsplit