In [2]:
# np.sort - Sort an array along a specified axis.
# resources link: https://numpy.org/doc/stable/reference/generated/numpy.sort.html
import numpy as np
a = np.random.randint(1,100,15)
a

array([45, 89, 91,  2, 54, 62, 29, 49, 31, 63, 13,  9, 66, 38, 71],
      dtype=int32)

In [3]:
np.sort(a)[::-1] # sort in descending order

array([91, 89, 71, 66, 63, 62, 54, 49, 45, 38, 31, 29, 13,  9,  2],
      dtype=int32)

In [4]:
b= np.random.randint(1, 100, 24).reshape(6,4)
b

array([[72, 24, 82, 86],
       [11,  4, 71, 23],
       [81, 96, 28,  1],
       [48, 49, 33, 39],
       [57, 63, 39,  5],
       [48, 97, 96, 87]], dtype=int32)

In [5]:
np.sort(b)
# row wise sorting

array([[24, 72, 82, 86],
       [ 4, 11, 23, 71],
       [ 1, 28, 81, 96],
       [33, 39, 48, 49],
       [ 5, 39, 57, 63],
       [48, 87, 96, 97]], dtype=int32)

In [6]:
np.sort(b, axis=0) # sort each column

array([[11,  4, 28,  1],
       [48, 24, 33,  5],
       [48, 49, 39, 23],
       [57, 63, 71, 39],
       [72, 96, 82, 86],
       [81, 97, 96, 87]], dtype=int32)

In [7]:
# np.append - Append values to the end of an array.
# resources link: https://numpy.org/doc/stable/reference/generated/numpy.append.html

a 

array([45, 89, 91,  2, 54, 62, 29, 49, 31, 63, 13,  9, 66, 38, 71],
      dtype=int32)

In [8]:
np.append(a, 2000) # append a single value

array([  45,   89,   91,    2,   54,   62,   29,   49,   31,   63,   13,
          9,   66,   38,   71, 2000])

In [9]:
b

array([[72, 24, 82, 86],
       [11,  4, 71, 23],
       [81, 96, 28,  1],
       [48, 49, 33, 39],
       [57, 63, 39,  5],
       [48, 97, 96, 87]], dtype=int32)

In [10]:
np.append(b, np.ones((b.shape[0],1)),axis=1) # append a column of ones to the end of the array

array([[72., 24., 82., 86.,  1.],
       [11.,  4., 71., 23.,  1.],
       [81., 96., 28.,  1.,  1.],
       [48., 49., 33., 39.,  1.],
       [57., 63., 39.,  5.,  1.],
       [48., 97., 96., 87.,  1.]])

In [11]:
# np.concatenate - Join a sequence of arrays along an existing axis.
# resources link: https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [12]:
np.concatenate((c,d), axis=0) # concatenate along rows (vertical stacking) 

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [13]:
np.concatenate((c,d), axis=1) # concatenate along columns (horizontal stacking)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [14]:
# np.unique - Find the unique elements of an array.
# resources link: https://numpy.org/doc/stable/reference/generated/numpy.unique.html

e = np.array([1,2,3,4,5,5,6,7,8,8,9])
e

array([1, 2, 3, 4, 5, 5, 6, 7, 8, 8, 9])

In [15]:
np.unique(e)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# np.expand_dims - Expand the shape of an array.   
# resources link: https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [17]:
np.expand_dims(a, axis=1) 
# adds a new axis at position 1, transforming the shape from (5,) to (5, 1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [18]:
np.expand_dims(a, axis=0) # add a new axis at the beginning (row vector)
# transforms the shape from (5,) to (1, 5)

array([[1, 2, 3, 4, 5]])

In [19]:
# np.where - Return elements chosen from x or y depending on condition.
# resources link: https://numpy.org/doc/stable/reference/generated/numpy.where.html
a = np.array([11,34,22,56,66,77,86,90,100])
a

array([ 11,  34,  22,  56,  66,  77,  86,  90, 100])

In [20]:
np.where(a > 50) # returns the indices of elements greater than 50

(array([3, 4, 5, 6, 7, 8]),)

In [21]:
np.where(a<50) # returns the indices of elements less than 50

(array([0, 1, 2]),)

In [22]:
np.where(a>50, 0, a) # replace elements greater than 50 with 0, keep others unchanged
# np.where(condition, true_value, false_value) 

array([11, 34, 22,  0,  0,  0,  0,  0,  0])

In [23]:
np.where(a%2==0, 0, a) 
# replace even numbers with 0, keep odd numbers unchanged

array([11,  0,  0,  0,  0, 77,  0,  0,  0])

In [24]:
# np.argmax - Returns the indices of the maximum values along an axis.
# resources link: https://numpy.org/doc/stable/reference/generated/numpy.argmax.html
a

array([ 11,  34,  22,  56,  66,  77,  86,  90, 100])

In [25]:
np.argmax(a) # returns the index of the maximum value in the array

np.int64(8)

In [26]:
b

array([[72, 24, 82, 86],
       [11,  4, 71, 23],
       [81, 96, 28,  1],
       [48, 49, 33, 39],
       [57, 63, 39,  5],
       [48, 97, 96, 87]], dtype=int32)

In [27]:
np.argmax(b, axis=0) # returns the indices of the maximum values along each column

array([2, 5, 5, 5])

In [28]:
np.argmax(b, axis=1) # returns the indices of the maximum values along each row

array([3, 2, 1, 1, 1, 1])

In [29]:
# np.argmin - Returns the indices of the minimum values along an axis.
# resources link: https://numpy.org/doc/stable/reference/generated/numpy.argmin.html

a

array([ 11,  34,  22,  56,  66,  77,  86,  90, 100])

In [30]:
np.argmin(a) # returns the index of the minimum value in the array

np.int64(0)

In [31]:
b

array([[72, 24, 82, 86],
       [11,  4, 71, 23],
       [81, 96, 28,  1],
       [48, 49, 33, 39],
       [57, 63, 39,  5],
       [48, 97, 96, 87]], dtype=int32)

In [32]:
np.argmin(b, axis=0) # returns the indices of the minimum values along each column

array([1, 1, 2, 2])

In [33]:
# np.cumsum - Return the cumulative sum of the elements along a given axis.
# resources link: https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

a

array([ 11,  34,  22,  56,  66,  77,  86,  90, 100])

In [34]:
np.cumsum(a) # returns the cumulative sum of the elements in the array

array([ 11,  45,  67, 123, 189, 266, 352, 442, 542])

In [35]:
b

array([[72, 24, 82, 86],
       [11,  4, 71, 23],
       [81, 96, 28,  1],
       [48, 49, 33, 39],
       [57, 63, 39,  5],
       [48, 97, 96, 87]], dtype=int32)

In [36]:
np.cumsum(b, axis=0) # returns the cumulative sum along each column

array([[ 72,  24,  82,  86],
       [ 83,  28, 153, 109],
       [164, 124, 181, 110],
       [212, 173, 214, 149],
       [269, 236, 253, 154],
       [317, 333, 349, 241]])

In [37]:
np.cumsum(b)

array([  72,   96,  178,  264,  275,  279,  350,  373,  454,  550,  578,
        579,  627,  676,  709,  748,  805,  868,  907,  912,  960, 1057,
       1153, 1240])

In [38]:
# cumprod - Return the cumulative product of the elements along a given axis.
# resources link: https://numpy.org/doc/stable/reference/generated/numpy.cumprod.html
np.cumprod(a) # returns the cumulative product of the elements in the array

array([              11,              374,             8228,
                 460768,         30410688,       2341622976,
           201379575936,   18124161834240, 1812416183424000])

In [39]:
# np.percentile - Compute the q-th percentile of the data along the specified axis.
# resources link: https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

a

array([ 11,  34,  22,  56,  66,  77,  86,  90, 100])

In [40]:
np.percentile(a,100) # returns the 100th percentile (max value) of the array

np.float64(100.0)

In [41]:
np.percentile(a, 50) # returns the 50th percentile (median) of the array

np.float64(66.0)

In [42]:
np.percentile(a, 25)

np.float64(34.0)

In [ ]:
# percentile means the value below which a given percentage of observations in a group of observations falls.
# like the 25th percentile is the value below which 25% of the observations may be found.

In [43]:
# np.histogram - Compute the histogram of a dataset.
# resources link: https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

a

array([ 11,  34,  22,  56,  66,  77,  86,  90, 100])

In [ ]:
np.histogram(a, bins=[0,10,20,30,40,50,60,70,80,90,100]) # returns the histogram of the array with 10 bins
    

(array([0, 1, 1, 1, 0, 1, 1, 1, 1, 2]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [48]:
np.histogram(a, bins=[0,50,100])

(array([3, 6]), array([  0,  50, 100]))

In [54]:
# np.correcoef - Return the Pearson product-moment correlation coefficients.
# resources link: https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html
# correlation coefficient is a measure of the linear relationship between two variables. It ranges from -1 to 1, where:
# -1 indicates a perfect negative linear relationship,
# 0 indicates no linear relationship,
# 1 indicates a perfect positive linear relationship.

salary = np.array([30000, 35000, 40000, 45000, 50000])
experience = np.array([1, 4, 3, 2, 4])
np.corrcoef(salary, experience) # returns the correlation coefficient matrix between salary and experience

array([[1.        , 0.48507125],
       [0.48507125, 1.        ]])

In [55]:
# np.isin - Test whether each element of an array is also present in a second array.
# resources link: https://numpy.org/doc/stable/reference/generated/numpy.isin.html

a

array([ 11,  34,  22,  56,  66,  77,  86,  90, 100])

In [56]:
items = [10,20,30,40,50,60,70,80,90,100]
np.isin(a, items) # returns a boolean array indicating whether each element of a is in items

array([False, False, False, False, False, False, False,  True,  True])

In [57]:
a[np.isin(a, items)] # returns the elements of a that are in items

array([ 90, 100])

In [58]:
# np.flip - Reverse the order of elements in an array along the given axis.
# resources link: https://numpy.org/doc/stable/reference/generated/numpy.flip.html

a

array([ 11,  34,  22,  56,  66,  77,  86,  90, 100])

In [59]:
np.flip(a) # returns a new array with the elements of a reversed

array([100,  90,  86,  77,  66,  56,  22,  34,  11])

In [60]:
b


array([[72, 24, 82, 86],
       [11,  4, 71, 23],
       [81, 96, 28,  1],
       [48, 49, 33, 39],
       [57, 63, 39,  5],
       [48, 97, 96, 87]], dtype=int32)

In [61]:
np.flip(b) # returns a new array with the elements of b reversed along all axes

array([[87, 96, 97, 48],
       [ 5, 39, 63, 57],
       [39, 33, 49, 48],
       [ 1, 28, 96, 81],
       [23, 71,  4, 11],
       [86, 82, 24, 72]], dtype=int32)

In [62]:
np.flip(b, axis=0) # returns a new array with the rows of b reversed (vertical flip)

array([[48, 97, 96, 87],
       [57, 63, 39,  5],
       [48, 49, 33, 39],
       [81, 96, 28,  1],
       [11,  4, 71, 23],
       [72, 24, 82, 86]], dtype=int32)

In [63]:
# np.put - Set elements of an array at specific indices.
# resources link: https://numpy.org/doc/stable/reference/generated/numpy.put.html

np.put(a, [0, 2, 4], [100, 200, 300]) # sets the elements at indices 0, 2, and 4 of array a to 100, 200, and 300 respectively

In [64]:
a

array([100,  34, 200,  56, 300,  77,  86,  90, 100])

In [65]:
# np.delete - Return a new array with sub-arrays along an axis deleted.
# resources link: https://numpy.org/doc/stable/reference/generated/numpy.delete.html    

a

array([100,  34, 200,  56, 300,  77,  86,  90, 100])

In [66]:
np.delete(a, [0, 2, 4]) # returns a new array with the elements at indices 0, 2, and 4 removed from array a

array([ 34,  56,  77,  86,  90, 100])

In [72]:
## Set function
  # - np.union1d
  # - np.intersect1d
  # - np.setdiff1d
  # - np.setxor1d
  # - np.in1d

m = np.array([1,2,3,4,5])
n = np.array([4,5,6,7,8])
print(np.union1d(m, n)) # returns the sorted unique elements that are in either m or n
print(np.intersect1d(m, n)) # returns the sorted unique elements that are in both m and n
print(np.setdiff1d(m, n)) # returns the sorted unique elements that are in m but not in n
print(np.setxor1d(m, n)) # returns the sorted unique elements that are in either m or n but not in both


[1 2 3 4 5 6 7 8]
[4 5]
[1 2 3]
[1 2 3 6 7 8]


In [78]:
# np.clip - Clip (limit) the values in an array.
# resources link: https://numpy.org/doc/stable/reference/generated/numpy.clip.html

a

array([100,  34, 200,  56, 300,  77,  86,  90, 100])

In [80]:
np.clip(a, a_min = 25, a_max = 75) # returns an array where values less than 0 are set to 0 and values greater than 50 are set to 50, while values between 0 and 50 remain unchanged

array([75, 34, 75, 56, 75, 75, 75, 75, 75])