### **Numpy array vs Python lists**

In [ ]:
# list
a = [i for i in  range(10000000)]
b = [i for i in  range(10000000, 20000000)]
c= []



In [16]:
import time
start = time.time()
for i in range(len(a)):
    c.append(a[i] + b[i])
print(time.time() - start)

2.296450614929199


In [17]:
# numpy

import numpy as np

a = np.arange(10000000)
b = np.arange(10000000, 20000000)

start = time.time()
c = a + b

print(time.time() - start)

0.3364708423614502


In [ ]:
'''
numpy is faster than list because it is 
implemented in C and uses optimized algorithms 
for operations like addition. Additionally,
numpy arrays are stored in contiguous memory
locations, which allows for faster access and
manipulation compared to lists, which are more 
flexible but less efficient for numerical operations.

''' 

In [24]:
# memory
a= [i for i in range(10000000)]
import sys

print(sys.getsizeof(a),"Byte")

89095160 Byte


In [ ]:
a = np.arange(10000000)
print(sys.getsizeof(a),"Byte") # default is int64, 8 Byte per element

80000112 Byte


In [28]:
a = np.arange(10000000, dtype=np.int32)
print(sys.getsizeof(a),"Byte")

40000112 Byte


In [29]:
a = np.arange(10000000, dtype=np.int8)
print(sys.getsizeof(a),"Byte")

10000112 Byte


### numpy  better than list because of
- 1. Speed
- 2. Memory Efficiency
- 3. Vectorized Operations

# **Advanced Indexing**

In [32]:
# normal indexing and slicing

a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
a[1,2]

np.int64(6)

In [34]:
a[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
# Fancy indexing
a

a[[0,1,2]] # row 0,1,2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
a = np.arange(24).reshape(6,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
a[[0,2,4,5]] # row 0,2,4,5

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
a[:,[0,2,3]] # all rows, column 0,2,3

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [ ]:
# Boolean indexing

In [ ]:
a = np.random.randint(1,100,24).reshape(6,4) 
# randint(low, high, size) -> low is inclusive, high is exclusive 
a

array([[47, 25, 83, 18],
       [96, 25, 11, 23],
       [30, 99, 40,  7],
       [86, 55,  7, 34],
       [34, 12,  1, 44],
       [67, 70, 46, 31]], dtype=int32)

In [44]:
# find all numbers greater than 50

a> 50

array([[False, False,  True, False],
       [ True, False, False, False],
       [False,  True, False, False],
       [ True,  True, False, False],
       [False, False, False, False],
       [ True,  True, False, False]])

In [ ]:
# boolean masking useing the above boolean array to filter the original array
a[a>50]
# here we are using the boolean array to index the original array, which returns only the elements that satisfy the condition (greater than 50 in this case).

array([83, 96, 99, 86, 55, 67, 70], dtype=int32)

In [46]:
# find all numbers greater than 50 and are even
a % 2 == 0

array([[False, False, False,  True],
       [ True, False, False, False],
       [ True, False,  True, False],
       [ True, False, False,  True],
       [ True,  True, False,  True],
       [False,  True,  True, False]])

In [ ]:
a[a % 2 == 0] # even numbers 

array([18, 96, 30, 40, 86, 34, 34, 12, 44, 70, 46], dtype=int32)

In [ ]:
a[(a>50) & (a % 2 == 0)] # numbers greater than 50 and are even

# & --- > bitwise and its use boolean operation on array

array([96, 86, 70], dtype=int32)

In [49]:
# find all numbers not divisible by 7

a[a%7 != 0]

array([47, 25, 83, 18, 96, 25, 11, 23, 30, 99, 40, 86, 55, 34, 34, 12,  1,
       44, 67, 46, 31], dtype=int32)